### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by mhr** [bazil/bazil#11]
I'm trying to install Bazil, and I got the following error while go getting Bazil.

`go version`

> go version go1.5 linux/amd64

`go get bazil.org/bazil`

>
    # bazil.org/bazil/util/grpcedtls
    ../bazil/util/grpcedtls/auth.go:24: cannot use (*Authenticator)(nil) (type *Authenticator) as type credentials.TransportAuthenticator in assignment:
    	*Authenticator does not implement credentials.TransportAuthenticator (wrong type for ClientHandshake method)
    		have ClientHandshake(string, net.Conn, time.Duration) (net.Conn, error)
    		want ClientHandshake(string, net.Conn, time.Duration) (net.Conn, credentials.AuthInfo, error)

**Comment by tv42** [comment]
As it says on the front page, grpc can't support the TLS auth we want, so bazil needs a custom grpc. See https://bazil.org/ -- unfortunate but ok for now.
