### ISSUE TITLE
Node.js client?

### ISSUE THREAD

**Issue by piranna** [bazil/bazil#17]
I have been interested on filesystems development from some years ago (and in fact I won a prize with my own one, [PirannaFS](https://github.com/piranna/PirannaFS) :-) ) and always I was a bit concern about the problems that `bazil` try to fix, with solutions like [mhddfs](https://romanrm.net/mhddfs) and so. Now for [NodeOS](https://github.com/NodeOS/NodeOS) I was willing to have each user its own `$HOME` on a remote server using WebDAV so their data is globally available and their local hard disk working as a cache... just as `bazil` is doing but with exteroids, so having something better available, why to write it from scratch? :-D So my question is, do you know if there's somewhere a Node.js client, or where should I start looking for to create my own one? :-)

**Comment by tv42** [comment]
It's way too early in the game for Bazil to be thinking of alternate clients.

**Comment by tv42** [comment]
This issue is both way too far out in the future and not really part of this repo to be kept open. I will not personally work on NodeJS clients, and will not guarantee disk or network format stability for a long time to come (if ever).
