### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by gudata** [bazil/bazil#19]
Hello,
What is the future of this project? Does anyone use it in his notebook? 

There is https://syncthing.net/ , any other alternatives?

**Comment by tv42** [comment]
As it says on https://bazil.org/

> Warning: at this stage in development, we will put no effort into compatibility of file formats or protocols. Do not stare into laser with remaining eye.

If you have to ask, it's _definitely_ not ready for you.

**Comment by fiatjaf** [comment]
Bazil has the opposite vision of Syncthing, Dropbox and so on, but if it is not ready, you may check git-annex or something from the list at https://git-annex.branchable.com/not/

**Comment by tv42** [comment]
BTW it might be worth using that I used to be a git-annex user, before I decided to work on bazil.
